version: '3.8'
services:
  # ===== DEVELOPMENT =====
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    # Mount the source code for hot-reloading
    # Use a named volume for node_modules to keep it isolated in the container
    volumes:
      - ./frontend:/app
      - /app/node_modules
    # The command to start the dev server. Vite config handles host, port, and file watching.
    command: npm run dev


# Named volumes for persistent data

# Custom network for all services
